/**
 * Pure validation for operator store provisioning (pre-deployment hardening).
 *
 * The operator creates a merchant Store through `scripts/create-store.ts`
 * (no AI, no customer surface). These helpers hold the rules so they are
 * unit-testable without a database; the script owns the DB work.
 *
 * Store fields here mirror the Prisma model: `name` (required), `slug`
 * (required, unique, URL-safe — used by merchants to identify the store),
 * optional `websiteUrl` / `logoUrl`. The id is generated by the existing
 * Prisma `@default(cuid())` — never by this code.
 */

export interface StoreProvisioningInput {
  name: string;
  slug: string;
  websiteUrl?: string;
  logoUrl?: string;
}

export type StoreProvisioningValidation =
  | { ok: true; value: Required<Pick<StoreProvisioningInput, "name" | "slug">> & StoreProvisioningInput }
  | { ok: false; field: "name" | "slug" | "websiteUrl" | "logoUrl"; reason: string };

/** 3–64 chars: lowercase letters, digits and hyphens; no edge hyphens. */
const SLUG_PATTERN = /^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$/;

const NAME_MAX = 120;
const URL_MAX = 500;

/** A usable URL is http(s) and short enough to store safely. */
function validateOptionalUrl(
  value: string | undefined,
  field: "websiteUrl" | "logoUrl",
): { ok: true } | { ok: false; field: "websiteUrl" | "logoUrl"; reason: string } {
  if (value === undefined) {
    return { ok: true };
  }
  const trimmed = value.trim();
  if (trimmed === "") {
    return { ok: true };
  }
  if (trimmed.length > URL_MAX) {
    return { ok: false, field, reason: "آدرس بیش از حد طولانی است." };
  }
  if (!/^https?:\/\//i.test(trimmed)) {
    return { ok: false, field, reason: "آدرس باید با http:// یا https:// شروع شود." };
  }
  return { ok: true };
}

/**
 * Validates (and normalizes) a provisioning request. The slug is lowercased
 * and trimmed before the pattern check, so «My-Shop» becomes «my-shop».
 */
export function validateStoreProvisioning(
  input: StoreProvisioningInput,
): StoreProvisioningValidation {
  const name = typeof input.name === "string" ? input.name.trim() : "";
  if (name === "") {
    return { ok: false, field: "name", reason: "نام فروشگاه الزامی است." };
  }
  if (name.length > NAME_MAX) {
    return { ok: false, field: "name", reason: "نام فروشگاه بیش از حد طولانی است." };
  }

  const slug = typeof input.slug === "string" ? input.slug.trim().toLowerCase() : "";
  if (slug === "") {
    return { ok: false, field: "slug", reason: "نامک فروشگاه (slug) الزامی است." };
  }
  if (!SLUG_PATTERN.test(slug)) {
    return {
      ok: false,
      field: "slug",
      reason:
        "نامک باید ۳ تا ۶۴ نویسهٔ لاتین کوچک، رقم یا خط تیره باشد و با خط تیره شروع یا تمام نشود.",
    };
  }

  const website = validateOptionalUrl(input.websiteUrl, "websiteUrl");
  if (!website.ok) {
    return website;
  }
  const logo = validateOptionalUrl(input.logoUrl, "logoUrl");
  if (!logo.ok) {
    return logo;
  }

  const websiteUrl = input.websiteUrl?.trim();
  const logoUrl = input.logoUrl?.trim();

  return {
    ok: true,
    value: {
      name,
      slug,
      ...(websiteUrl ? { websiteUrl } : {}),
      ...(logoUrl ? { logoUrl } : {}),
    },
  };
}
